import math
import pandas as pd

def calculate_ochiai(fail_executed: int, pass_executed: int, total_failed: int, total_passed: int) -> float:
    """
    Computes the Ochiai suspiciousness score.
    """
    if total_failed == 0 or (fail_executed + pass_executed) == 0:
        return 0.0
    
    denominator = math.sqrt(total_failed * (fail_executed + pass_executed))
    return float(fail_executed / denominator)

def calculate_tarantula(fail_executed: int, pass_executed: int, total_failed: int, total_passed: int) -> float:
    """
    Computes the Tarantula suspiciousness score.
    """
    if total_failed == 0:
        return 0.0
        
    fail_ratio = fail_executed / total_failed
    pass_ratio = pass_executed / total_passed if total_passed > 0 else 0.0
    
    denominator = fail_ratio + pass_ratio
    if denominator == 0:
        return 0.0
        
    return float(fail_ratio / denominator)

def compute_sbfl_scores_from_csv(coverage_csv_path: str) -> pd.DataFrame:
    """
    Reads a coverage CSV (generated by GZoltar or synthetically) and computes statement-level
    and method-level SBFL metrics (Ochiai, Tarantula) using fully vectorized operations.
    Returns a DataFrame grouped by method name.
    """
    df = pd.read_csv(coverage_csv_path)
    if 'Result' not in df.columns:
        raise ValueError("Coverage CSV missing 'Result' column.")
        
    passing_df, failing_df = df[df['Result'] == 'Pass'], df[df['Result'] == 'Fail']
    total_pass, total_fail = len(passing_df), len(failing_df)
    
    pass_counts = passing_df.drop(columns=['Result']).sum()
    fail_counts = failing_df.drop(columns=['Result']).sum()
    
    s_df = pd.DataFrame({
        'Stmt': pass_counts.index,
        'Pass_Executed': pass_counts.values,
        'Fail_Executed': fail_counts.values
    })
    
    s_df['Ochiai'] = s_df.apply(lambda r: calculate_ochiai(r['Fail_Executed'], r['Pass_Executed'], total_fail, total_pass), axis=1)
    s_df['Tarantula'] = s_df.apply(lambda r: calculate_tarantula(r['Fail_Executed'], r['Pass_Executed'], total_fail, total_pass), axis=1)
    
    s_df['Method'] = s_df['Stmt'].apply(lambda s: s.split(':')[0].replace('$', '.'))
    
    method_df = s_df.groupby('Method').agg({
        'Ochiai': 'max', 
        'Tarantula': 'max',
        'Fail_Executed': 'sum'
    }).reset_index()
    
    # Filter out test methods since they are no longer included in the call graph
    method_df = method_df[~method_df['Method'].str.contains('Test', case=False)]
    
    return method_df
