import os
from pathlib import Path
import pandas as pd
import logging
from dataclasses import dataclass
from typing import List, Dict, Any

from benchmarking.d4j_manager import D4JManager
from benchmarking.gzoltar_manager import GZoltarRunner
from graph_generation.sbfl.tracer_runner import TracerRunner
from graph_generation.sbfl.call_graph_parser import parse_raw_call_graph, save_to_json
from benchmarking.sbfl_metrics import calculate_ochiai, calculate_tarantula, compute_sbfl_scores_from_csv

logger = logging.getLogger(__name__)

@dataclass
class ExtractionResult:
    graph_json: str
    sbfl_metrics: List[Dict[str, Any]]
    buggy_methods: List[str]
    
    def validate(self) -> None:
        if not Path(self.graph_json).exists():
            raise FileNotFoundError(f"Generated graph JSON missing: {self.graph_json}")
        if not self.sbfl_metrics:
            raise ValueError("SBFL metrics list is empty.")
        if not self.buggy_methods:
            logger.warning("No buggy methods identified. Ground truth may be missing.")

class SBFLGraphExtractor:
    def __init__(self, d4j_path: str, java_home: str):
        self.d4j_manager = D4JManager(d4j_path, java_home)
        
        current_dir = Path(__file__).parent
        
        gzoltar_path = current_dir / "gzoltar"
        if not gzoltar_path.exists():
            raise FileNotFoundError(f"GZoltar directory missing: {gzoltar_path}")
        self.gzoltar_runner = GZoltarRunner(str(gzoltar_path), java_home)
        
        tracer_path = current_dir / "tracer_agent"
        if not tracer_path.exists():
            raise FileNotFoundError(f"Tracer directory missing: {tracer_path}")
        self.tracer_runner = TracerRunner(str(tracer_path))
        
    def extract(self, project: str, bug_id: str, output_dir: str, package_prefix: str) -> ExtractionResult:
        output_path = Path(output_dir)
        output_path.mkdir(parents=True, exist_ok=True)
        work_dir = output_path / "workspace"
        
        logger.info(f"Extracting {project}-{bug_id}")
        
        agent_jar = self.tracer_runner.compile_agent()
        
        if not work_dir.exists():
            self.d4j_manager.checkout(project, bug_id, str(work_dir))
            self.d4j_manager.compile(str(work_dir))
            
        props = self.d4j_manager.get_properties(str(work_dir))
        if "cp.test" not in props:
            raise ValueError(f"Failed to extract properties for {project}-{bug_id}")
            
        cp = props["cp.test"]
        
        if 'dir.bin.classes' not in props:
            raise ValueError(f"Property 'dir.bin.classes' not found for {project}-{bug_id}")
        if 'dir.bin.tests' not in props:
            raise ValueError(f"Property 'dir.bin.tests' not found for {project}-{bug_id}")
            
        src_classes = work_dir / props['dir.bin.classes']
        test_bin = work_dir / props['dir.bin.tests']
        
        tests_file = output_path / "tests.txt"
        gzoltar_output = output_path / "gzoltar-out"
        coverage_csv = output_path / "coverage.csv"
        
        if not coverage_csv.exists():
            if not tests_file.exists():
                self.gzoltar_runner.list_tests(str(test_bin), cp, str(tests_file))
            if not tests_file.exists():
                raise FileNotFoundError("Tests file was not generated by GZoltar.")
                
            self.gzoltar_runner.collect_coverage(str(work_dir), str(src_classes), cp, str(tests_file), str(gzoltar_output), "*", "*Test*:*junit*")
            self.gzoltar_runner.export_to_csv(str(gzoltar_output), str(coverage_csv))
            
        if not coverage_csv.exists():
            raise FileNotFoundError("Coverage CSV was not generated by GZoltar.")
            
        raw_graph_txt = output_path / "call_graph.txt"
        if not package_prefix:
            raise ValueError("package_prefix must be explicitly provided and cannot be empty.")
            
        if not raw_graph_txt.exists():
            self.d4j_manager.run_test_with_agent(str(work_dir), str(agent_jar), f"{raw_graph_txt};{package_prefix}")
            
        if not raw_graph_txt.exists():
            raise FileNotFoundError("Dynamic call graph was not generated by TracerAgent.")
            
        graph_json = output_path / "call_graph.json"
        graph = parse_raw_call_graph(str(raw_graph_txt))
        
        # Filter out <clinit> and Test classes so that only source methods remain
        graph.nodes = [n for n in graph.nodes if "<clinit>" not in n and "Test" not in n]
        graph.edges = [e for e in graph.edges if "<clinit>" not in e.caller and "<clinit>" not in e.callee
                       and "Test" not in e.caller and "Test" not in e.callee]
        
        graph.metadata.total_nodes = len(graph.nodes)
        graph.metadata.total_edges = len(graph.edges)
        
        save_to_json(graph, str(graph_json))
        
        method_df = compute_sbfl_scores_from_csv(str(coverage_csv))
        metrics_csv = output_path / "sbfl_metrics.csv"
        method_df.to_csv(metrics_csv, index=False)
        
        result = ExtractionResult(
            graph_json=str(graph_json),
            sbfl_metrics=method_df.to_dict(orient="records"),
            buggy_methods=self.d4j_manager.get_buggy_methods(project, bug_id, str(work_dir))
        )
        result.validate()
        return result
